### ISSUE TITLE
ignore folders and/or ignore .git folder by default

### ISSUE THREAD

**Issue by fuzetsu** [lukejacksonn/servor#10]
If I start servor at the root of my git repo a refresh is triggered whenever I run `git status`, `git add`, `git commit ` etc.

It's not a huge issue, but there's no way currently of specifying folders for the watch to ignore. It might be nice to include such an option, it might also make sense to ignore some common folders like `.git` or `node_modules`.

**Comment by lukejacksonn** [comment]
Yes, I have noticed this too.. but I kind of like it 😅 especially when working on projects with no build step.. I just pull down a branch or PR and it just loads in my browser!

Unless there is an issue with perf then I'd rather not ignore anything by default. I'd consider adding an option if there was more demand for such a feature.

**Comment by fuzetsu** [comment]
Ah, fair enough, switching branches is a good one, I like that :laughing:

I guess we should leave this open to see if anyone is interested?

**Comment by lukejacksonn** [comment]
Yep. Happy to leave it open for a bit!

**Comment by lukejacksonn** [comment]
Doesn't look like this is causing anyone any trouble so I am going to close here!

**Comment by rbiggs** [comment]
Actually, I would like a way to ignore folder. I'm using Servor with Gulp. I have an index.html at the root of my project. Then I have a src and a dist. The src files are being watched by gulp for changes. When I modify and save them in my editor, gulp rebuilds them and outputs them to dist. Problem is Servor reloads when I save changes in src and when the new build is output to dist. That a lot of unnecessary reloading going on. Very annoying. I want to be able to ignore my src directory.

**Comment by lukejacksonn** [comment]
Hey @rbiggs thanks for the feedback here! I'm not sure but couldn't you start servor from within the `dist` directory? That way it shouldn't pick up changes in src and should only reload when gulp has finished doing its thing..

**Comment by rbiggs** [comment]
Well, technically putting the index.html file into the dist folder and just watching the dist folder works. However, the dist folder and its contents are not there when I create a new project. They get created by the build script. So index.html lives at the root of the project. Any way, this isn't a life or death issue. It's just an annoying nit pick. 🤔

Having a way to ignore files/folders would be nice and solve such issues.

**Comment by lukejacksonn** [comment]
In my experience build steps will often move the index.html into the dist folder too.. but I get your point. The reason I am pushing back on this, is that it is a very awkward option to input via a CLI. It would be much more suited to having in a config file like a `.babelrc` or `netlify.toml` which I am not massively opposed to but is a different conversation.
