### ISSUE TITLE
Specify port without fallback?

### ISSUE THREAD

**Issue by lazarljubenovic** [lukejacksonn/servor#11]
I appreciate the simplicity of the command without too many flags, but I change the port much often than I change the fallback file. In fact, I've never changed the fallback file :sweat_smile: 

Would love to see `--port` so I can do `yarn servor dist --port 3001` instead of `yarn servor dist dist/index.html 3001`.

**Comment by lukejacksonn** [comment]
Fair point. Positional arguments are a pain especially when it comes to adding more arguments. Do you know of a nice clean way to parse these kind of flags? Keeping in mind this lib is currently dependency free (and I'd kinda like it to remain that way)!

**Comment by lazarljubenovic** [comment]
Maybe we could guess that an integer number is a port?

**Comment by lukejacksonn** [comment]
That sounds a little brittle (for example what if someone had a project called 123). I'd prefer a flag than making guesses, I just never found a very clean way of extracting them out of the command 🤔
