### ISSUE TITLE
unpkg CDN as a fallback?

### ISSUE THREAD

**Issue by osdevisnot** [lukejacksonn/servor#13]
Hi @lukejacksonn, first off, thank you so much for putting this together. 

While using `servor` for my prototype work, I wanted an ability to use `servor` without even npm installing my dependencies 🎉 🎉 

One way I was thinking to solve this, is by adding a check in `servor` to see if we are serving a JS file. If a JS file is not available locally, we rewrite the URL to UNPKG CDN URL.

For Example:

Let's say I have code like this in say `index.js`:

```js
import { patch, h } from 'superfine';
import store from '@vanillajs/store';
```

`servor` would rewrite this to something like this (when `node_modules` is not available):

```js
import { patch, h } from 'https://unpkg.com/superfine@6.0.1?type=module';
import store from 'https://unpkg.com/@vanillajs/store@0.1.7?type=module';
```

To take it a step further, if I do not have `package.json`, we simply rewrite the URL to something like this:

```js
import { patch, h } from 'https://unpkg.com/superfine?type=module';
import store from 'https://unpkg.com/@vanillajs/store?type=module';
```

This idea has been explored before with [owc-dev-server](https://github.com/open-wc/open-wc/tree/master/packages/owc-dev-server#resolves-node-style-module-imports-to-browser-style) and works quite well using [express-transform-bare-module-specifiers](https://github.com/nodecg/express-transform-bare-module-specifiers)

However, I would like a no-dependency solution for this to be available in `servor`

thoughts/concerns?

**Comment by lukejacksonn** [comment]
I think this is a really interesting idea and would like to see it evolve. Currently I use servor with es module only projects (without local dependencies) and currently manage by being explicit about my import urls so doing `https://unpkg.com/es-react` for example.

But it would be nice not to have to write `https://unpkg.com` everywhere. You might be interested in a few other threads that I have been having with developers in other bundler camps (pikapkg and webpack) over in https://github.com/lukejacksonn/perflink/issues/15

**Comment by osdevisnot** [comment]
Awesome, I'll try to get to this soon. We will need to explore if this can bring any unforeseen hurdles if we make it a default. Alternative would be to have a flag to disable this behavior.

**Comment by osdevisnot** [comment]
Digging deeper on this, it seems we have 2 alternative approaches we can go with. 

First approach would be to use `@babel/core` with `babel-plugin-bare-import-rewrite
` and follow what `express-transform-bare-module-specifiers` does. Something like this:
```
				const result = babel.transformSync(body, {
					filename: path.resolve(rootDir, request.path.replace(/^\//, '')),
					plugins: [
						['bare-import-rewrite', {
							modulesDir: modulesUrl,
							rootBaseDir: rootDir
						}]
					],
					sourceMaps: 'inline'
				});
```

Second approach would be to use :scream::scream: REGEX :scream::scream: to replace the file content before sending a response. Something like this:

https://regex101.com/r/6mZUJu/1

Babel approach would add a dependency to `servor`, which kind of defeats the no-dependency constraints. However REGEX can be hard to read and add maintenance overhead.

**Comment by lukejacksonn** [comment]
The regex route sounds much more adoptable at this point. I have written one like this before.. it wasn't _too_ bad but I probably missed some edge cases.

**Comment by lukejacksonn** [comment]
Hey @osdevisnot if you figure this out then please open a PR and reference this issue. I'm very interested in what it might look like but am doing a tidy up here so am going to close for now!
