### ISSUE TITLE
BaseUrl support?

### ISSUE THREAD

**Issue by Airkro** [lukejacksonn/servor#16]
As a simplicity project, `servor` is excellent and very easy to use.

But do you have plans to support `baseUrl`?

Considering that many people will use webpack( `options.output.publicPath` or others), I think this option is very useful to support SPA development/preview.

Then we can:

```bash
servor dist --baseUrl admin
```

↓↓

```
http://localhost:8080/          --> Error 404 or Friendly Tips.
http://localhost:8080/admin/    --> ./dist/index.html
```

**Comment by lukejacksonn** [comment]
Hey 👋🏼 although I have seen tis feature in other servers I have not thought too much about it, although I have come across a case where I have needed to serve from a root directory to access say an `index.js` but the `index.html` was inside a directory like `test`. So I served from root and just visited `localhost:8080/test/index.html` but that broke live reload.. perhaps this option would fix that.

Fancy making a PR?

**Comment by lukejacksonn** [comment]
Hey @Airkro did you find a nice solution to this at all? I am going to close here because this issue has been inactive for a while now and I have still not found the need for such a feature.

Happy to discuss again if you found a workaround!

**Comment by ruudud** [comment]
Necrobumping this one, as I think this feature would be very useful.
When working with SPAs deployed to GitHub pages, you'd typically get the base URL `username.github.io/reponame`. Coupling the "reponame" into the directory structure of the repo itself feels strange and fiddly, and also causes problems when working with bundlers that rewrites import paths (like Snowpack via Babel and Rollup).

Please reconsider. :-)

**Comment by lukejacksonn** [comment]
I also deploy to GitHub Pages a lot and feel your pain.. usually I end up adding a custom domain to rid myself of the `/reponame` pathname. I haven't tried solving it with baseUrl. Will give it another go when I have some time.

Feel free to PR. I'd be more than happy to talk about or review it!

**Comment by lukejacksonn** [comment]
Hey all :wave: this is _kinda_ doable now.. if you run V4 with `--static` then you can visit nested directories and if they have an `index.html` in then it will be loaded. which means if you setup a project called `pages` for example and then run:

```
npx servor gh:<HANDLE>/<REPO> --browse --editor --reload
```

Then a browser then visiting `/` will actually serve `/<REPO>` with a base url injected. Its not perfect I know but maybe it is workable?

Thanks for the suggestion and let me know what you think!
