### ISSUE TITLE
Opt-out of automatically opening url

### ISSUE THREAD

**Issue by mrozbarry** [lukejacksonn/servor#17]
In some cases, like running along side Cypress, I don't need Chrome to auto-open, since Cypress has it's own isolated browser. Would it be possible to have a `--no-open` flag to prevent this feature. I think it's fine and usually preferable as a default to open, so I think the flag just needs to be for opt-out of this behaviour rather than opt-in.

**Comment by lukejacksonn** [comment]
This is essentially a duplication on #14 but hits home the fact that this is an in demand feature so I am going to close this and mark the other as a priority 👍
