### ISSUE TITLE
Service Workers

### ISSUE THREAD

**Issue by flasaracina** [lukejacksonn/servor#25]
Hello!
I am using servor for a web application I am building and I was wondering if there is an option to set up the `service-worker-allowed` for the site service worker.

Thanks in advance

**Comment by lukejacksonn** [comment]
Hey, apologies for the late reply. I have been on vacation 🏖

This sound reasonable. I didn't know `service-worker-allowed` was a thing tbh! We could add that header when JS files are on their way out?

**Comment by flasaracina** [comment]
oh, no worries! Hope you had great time on vacation! :)

`service-worker-allowed` header should be only set when serving a service worker file. Since you can have multiple service workers for a single site, I think it would be nice if we can configure it somehow. I was thinking about something along the lines of:

`servor ./ ./index.html 3000 3001 --no-reload --sw-scopes ./sw.js=/ ./sample/sw.js=/`

or something like that. I know you can come uo with a clever idea on how to configure that header per service-worker path.

Thank you very much and keep up with the good work! It's much appreciated

**Comment by lukejacksonn** [comment]
Humm, that seems a little more involved.. would putting it on every request break the site or service worker?

**Comment by flasaracina** [comment]
It will not break anything, I think. That header is there only to tell the browser how to setup the service worker. There is only one real problem I see, that is  you can have multiple service workers on a site (with a unique scope each). If you just spit that header out on every request, It'll be impossibile to customize multiple service workers behaviour.

**Comment by lukejacksonn** [comment]
Ok, do you think a service worker file naming convention (like `*.sw.js`) could work?

**Comment by flasaracina** [comment]
I think it will. But how do you customize the value of that header per service worker served?

**Comment by lukejacksonn** [comment]
This isn't really something I have looked into too deeply.. perhaps you could point me in the right direction of some good examples/documentation for this kind of setup?

**Comment by lukejacksonn** [comment]
So.. yesterday I tried adding a service worker to a site I was developing on using servor and it seemed to work just fine.. what issue were/are you actually experiencing?

**Comment by flasaracina** [comment]
Try to add a service worker file in a sub folder and try to give it `/` as a scope (the whole site)

It shouldn't work because the scope of a service worker MUST be of the same folder hierarchy or lower. If your service worker file resides in a subfolder,  it cannot handle calls that originate from scripts that reside in a higher hierarchy (let's say root, for example)

**Comment by lukejacksonn** [comment]
Ahhh.. I see! That makes sense. I have never had more than one service worker or wanted them to have different scopes. Seems like it would be hard to input that kind of config on CLI 🤔

**Comment by flasaracina** [comment]
I see. What do you think about the sample configuration I come up with in my second comment
[here](https://github.com/lukejacksonn/servor/issues/25#issuecomment-527932901) ?

Do you think it's doable as a starter? Just to have such functionality?

Thank you for your time ;)

**Comment by lukejacksonn** [comment]
I think you could almost definitely set this up in a fork! Check out this PR which adds cors headers https://github.com/lukejacksonn/servor/pull/3/files it might give you some clues as where to get started.

**Comment by lukejacksonn** [comment]
Hey @flasaracina did you figure out a nice solution to this issue? I am going to close here as it has been inactive for a while and I still haven't come across any issues with service workers myself (probably because I am just using them at the root of my project).

Happy to discuss again though if you have found a nice workaround!
