### ISSUE TITLE
--reload causes browsers to enter quirks mode

### ISSUE THREAD

**Issue by jakedeichert** [lukejacksonn/servor#46]
When using the `--reload` option, the browser _disobeys_ the specified doctype I have. This is apparently because placing any content before the doctype [forces the browser into quirks mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode).

> Make sure you put the DOCTYPE right at the beginning of your HTML document. Anything before the DOCTYPE, like a comment or an XML declaration will trigger quirks mode in Internet Explorer 9 and older.

Well... this happens to break Safari, Firefox and Chrome for me in weird ways. It led me to write invalid/incomplete flexbox css which is broken in standards mode 😅 . After doing a non-dev build, I found out a lot of my site was messed up. 

This is what the browser is receiving:
<img width="566" alt="before doctype" src="https://user-images.githubusercontent.com/1631044/79823802-93ec6c00-8362-11ea-801f-dc1530870633.png">

[These are the two problem lines](https://github.com/lukejacksonn/servor/blob/93821826c1170546d3c45eb234fbc69e61971c9d/servor.js#L104-L105) that can cause this behaviour. 

```js
if (isRoute && inject) file = inject + file;
if (isRoute && reload) file = livereload + file;
```

### Possible solution
Would doing `file + livereload` work instead maybe?

**Comment by lukejacksonn** [comment]
Hey man! Thanks for reporting this and for your patience. I just published `[3.3.1](https://runpkg.com/servor@3.3.1)` which has the fix you suggest in it plus gzip.

Hope this helps (I'm wondering how long I've been developing in quirks mode now.. doh) 🙇

**Comment by jakedeichert** [comment]
Sweet, thanks for merging that! 

I had a fixed copy of servor in my project but can update to this version now 😅

**Comment by lukejacksonn** [comment]
I figured most people would have done that and I wanted to get some other stuff in at the same time so it took longer than it should have. Anyway happy to help though and thanks for the support!
