### ISSUE TITLE
Option for disable the injection of base tag

### ISSUE THREAD

**Issue by MeloJR** [lukejacksonn/servor#52]
With the new version when I reload a custom route (for example `/profile`) servor injects a `<meta charset="UTF-8" > and a `<base href="\profile\">` tags at the start of my index.html, so my files are not found because they expect that base has to be "/".

Can I use any option to disable this behavior?

**Comment by lukejacksonn** [comment]
Hey 👋 in my tests I haven't found this breaking any old behaviour.. are you using the `--static` flag? If so.. then I'd expect to see this but otherwise I'd expect the injected base tag to just be:

```
<base href="/">
```

Which shouldn't cause any issues 🤔 have you got a demo?

**Comment by lukejacksonn** [comment]
Oh damn.. I see this now 😅 wow how did I miss this! Will fix now 👍

**Comment by lukejacksonn** [comment]
Hopefully that does it for you @MeloJR thanks for reporting the issue so promptly. Apologies for the breakage, please let me know if it didn't resolve your issue 🙇

**Comment by MeloJR** [comment]
Now it works perfectly! Thank you so much!
