### ISSUE TITLE
servor crashes on st terminal in Ubuntu

### ISSUE THREAD

**Issue by rajasegar** [lukejacksonn/servor#66]
Running servor crashes the st terminal in Ubuntu 20.10
https://st.suckless.org/

**Comment by lukejacksonn** [comment]
Humm, I'm not familiar with st terminal. If you could provide a little more context that would be good otherwise I don't myself have a ubuntu machine so it might be hard for me to debug. Apologies!

**Comment by rajasegar** [comment]
I am really not sure this is the problem with servor or the st terminal. Let me look for any logs from the st terminal side I can find and unravel more information regarding this issue. You can find the st terminal here https://st.suckless.org/
And If I start servor inside it, the terminal crashes and vanishes away without any info.

**Comment by lukejacksonn** [comment]
Interesting, LMK what you find!

**Comment by rajasegar** [comment]
Found the root cause, it is not because of servor, but the rendering of emojis in st. More info here
https://wiki.archlinux.org/index.php/St#Crashes_if_page_contains_emoji_characters
So installing the `fonts-symbola` resolved the issue for me. Hence closing this issue.

**Comment by lukejacksonn** [comment]
Awesome, thanks for looking into this. Hopefully your findings will help someone in the future!
